name: Release for the project
on: push
jobs :
 release-project:
  name: Release project to github release
  runs-on: ubuntu-latest
  needs: build-project
  steps:
  
    - name: Chekout the repo
      uses: actions/checkout@v2
    - name: Print the dir
      run: dir
    - name: Read release.zip and use it as a body of new release
      run: |
       r=$(cat path/to/release.zip)
       r="${r//'%'/'%25'}"
       r="${r//$'\n'/'%0A'}"                           
       r="${r//$'\r'/'%0D'}"                             
       echo "::set-output name=RELEASE_BODY::$r"   
    - name: Upload Binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
    - name: Create Github Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release V${{ github.run_number }}
        
 build-project:
       name: Build project
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3
         - name: create release
           run: zip -r release.zip .
         - name: upload a project
           uses: actions/upload-artifact@v2
           with:
            name: project
            path: out/
