name: Release for the project
on: push
jobs :
 release-project:
  permissions: write-all
  name: Release project to github release
  runs-on: ubuntu-latest
  steps:
    - name: Create Github Release
      uses: actions/create-release@v1
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
         
