name: Release for the project
on: 
 push:
  branches: [ main ]
jobs :
 release-project:
  permissions: write-all
  name: Automated project release
  runs-on: ubuntu-latest
  steps:
    - name: Chekout the repo
      uses: actions/checkout@v2
    - name: Print the dir before creating the zip file
      run: dir
    - name: create release
      run: zip -r release.zip .
    - name: Print the dir after created zip file
      run: dir
    - name: Create Github Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release V${{ github.run_number }}  
      
    - name: upload a asset to release attachment
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release.zip
        asset_name: Release.zip
        asset_content_type: application/zip
  
